name: Create and publish a Docker image

#on: push
on:
 workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: env_emage_name
# IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
#       uses: actions/checkout@v3
      - name: Checkout repository
        uses: actions/checkout@master
        
#       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            
#       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
